service:
  type: ClusterIP
  port: 8080

mysql:
  enabled: false

env:
  RETAIL_CATALOG_PERSISTENCE_PROVIDER: mysql

  RETAIL_CATALOG_PERSISTENCE_ENDPOINT:  

  RETAIL_CATALOG_PERSISTENCE_DB_NAME: bedrock_catalog_db

  RETAIL_CATALOG_PERSISTENCE_USER:

  RETAIL_CATALOG_PERSISTENCE_PASSWORD:

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi