service:
  type: ClusterIP
  port: 8080

env:
  - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
    value: mysql

  - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
    value: mysql

  - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
    value: bedrockdb

  - name: RETAIL_CATALOG_PERSISTENCE_USER
    value: bedrockuser

  - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
    value: bedrockpass

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi