service:
  type: ClusterIP
  port: 8080

env:
  - name: RETAIL_CATALOG_PERSISTENCE_PROVIDER
    value: mysql

  - name: RETAIL_CATALOG_PERSISTENCE_ENDPOINT
    value: project-bedrock-mysql20260213104821097600000005.cmvmoygy4sqk.us-east-1.rds.amazonaws.com:3306

  - name: RETAIL_CATALOG_PERSISTENCE_DB_NAME
    value: bedrock_catalog_db

  - name: RETAIL_CATALOG_PERSISTENCE_USER
    value: 

  - name: RETAIL_CATALOG_PERSISTENCE_PASSWORD
    value: 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi