service:
  type: ClusterIP
  port: 8080

env:
  - name: RETAIL_ORDERSSTENCE_PROVIDER
    value: postgres

  - name: RETAIL_ORDERS_PERSISTENCE_ENDPOINT
    value: project-bedrock-postgresql2026021320562769780000000a.cmvmoygy4sqk.us-east-1.rds.amazonaws.com:5432

  - name: RETAIL_ORDERS_PERSISTENCE_DB_NAME
    value: bedrock_order_db

  - name: RETAIL_ORDERS_PERSISTENCE_USER
    value: 

  - name: RETAIL_ORDERS_PERSISTENCE_PASSWORD
    value: 

  - name: RETAIL_ORDERS_MESSAGING_PROVIDER
    value: rabbitmq

  - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_ADDRESSES
    value: rabbitmq:5672

  - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_USERNAME
    value: 

  - name: RETAIL_ORDERS_MESSAGING_RABBITMQ_PASSWORD
    value: 

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
