apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dynamodb.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}