apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: amqp
      port: {{ .Values.service.amqpPort }}
      targetPort: amqp
    - name: management
      port: {{ .Values.service.managementPort }}
      targetPort: management
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
