name: Deploy Helm Charts to EKS Cluster

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-helm.yaml
      - ./helm/**
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
  NAMESPACE: retail-app

jobs:
  deploy-helm:
    name: Deploy Helm Charts to EKS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.14.0'

      # - name: Create namespace
      #   run: |
      #     kubectl create namespace ${{ env.NAMESPACE }} || echo "Namespace '${{ env.NAMESPACE }}' already exists"

      # - name: Login to ECR Public
      #   run: |
      #     aws ecr-public get-login-password --region ${{ env.AWS_REGION }} \
      #     | helm registry login --username AWS --password-stdin public.ecr.aws

      - name: Change to helm directory
        run: |
          cd ./helm
          chmod +x deploy.sh

      - name: Deploy Helm Charts
        run: |
          ./deploy.sh



      # - name: Login to Public ECR
      #   run: |
      #     aws ecr-public get-login-password --region ${{ env.AWS_REGION }} \
      #     | helm registry login --username AWS --password-stdin public.ecr.aws
 
      # -  name: Deploy with Helm
      #    uses: bitovi/github-actions-deploy-eks-helm@v1.2.12
      #    with:
      #      aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
      #      aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
      #      aws-region: ${{ env.AWS_REGION }}
      #      cluster-name: ${{ env.EKS_CLUSTER_NAME }}
      #      chart-path: public.ecr.aws/aws-containers/retail-store-sample-ui-chart:1.4.0
      #      namespace: ${{ env.NAMESPACE }}
      #      values: ./helm/ms-values/frontend-values.yaml
      #      name: frontend

      # - name: Deploy Catalog
      #   run: |
      #     helm upgrade --install catalog \
      #       oci://public.ecr.aws/aws-containers/retail-store-sample-catalog \
      #       --version 1.4.0 \
      #       --namespace ${{ env.NAMESPACE }} \
      #       --wait \
      #       --timeout 5m

      # - name: Deploy Cart
      #   run: |
      #     helm upgrade --install cart \
      #       oci://public.ecr.aws/aws-containers/retail-store-sample-cart \
      #       --version 1.4.0 \
      #       --namespace ${{ env.NAMESPACE }} \
      #       --wait \
      #       --timeout 5m

      # - name: Deploy Orders
      #   run: |
      #     helm upgrade --install orders \
      #       oci://public.ecr.aws/aws-containers/retail-store-sample-orders \
      #       --version 1.4.0 \
      #       --namespace ${{ env.NAMESPACE }} \
      #       --wait \
      #       --timeout 5m

      # - name: Deploy Checkout
      #   run: |
      #     helm upgrade --install checkout \
      #       oci://public.ecr.aws/aws-containers/retail-store-sample-checkout \
      #       --version 1.4.0 \
      #       --namespace ${{ env.NAMESPACE }} \
      #       --wait \
      #       --timeout 5m

      # - name: Verify Deployments
      #   run: |
      #     kubectl get all -n ${{ env.NAMESPACE }}
      #     helm list -n ${{ env.NAMESPACE }}
     